language: android

android:
  components:
    - tools
    - build-tools-25.1.0
    - extra-android-m2repository
    - android-25
  licenses:
    - android-sdk-license-.+

jdk:
  - oraclejdk7

script:
  - ./gradlew clean build

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
