language: android

android:
  components:
    - build-tools-23.0.1
    - extra-android-m2repository
    - android-23
  licenses:
    - android-sdk-license-.+

jdk:
  - oraclejdk7

script:
  - ./gradlew clean build

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
